name: Code quality
on:
  push:
    branches: [ main ]
  pull_request:

  workflow_dispatch:

jobs:
  check_code_quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
        python -m pip install nox_poetry
    - name: Assess code quality
      run: nox -s style_checking

  doc_quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install poetry
        python -m pip install nox_poetry
        poetry install -v
    - name: Check doc quality
      run: |
        poetry run pflake8 --select "D102,103" strawman/
        nox -s build_docs
